config/routes.rb
Rails.application.routes.draw do


  devise_for :users


  devise_scope :user do
    authenticated :user do
      root 'sportactions#ranking', as: :authenticated_root
      get 'ranking' => 'sportactions#ranking'
      get 'pages/about'
      resources :pages, only: [:new, :create, :show]
      resources :sports, only: [:index, :new, :create, :show]
      resources :sportactions, only: [:new, :create, :index ,:destroy]
      resources :employees, only: [:new, :create]
      # post 'prizes/index' => 'prizes#get_random_ticket'
      # post 'prizes/show' => 'prizes#save_ticket_to_prize'
      # post 'destroy' => 'prizes#destroy', as: :destroy
      # post 'update' => 'tickets#update'
      # get 'list' => 'prizes#list'
      # root 'prizes#index', as: :authenticated_root
    end


    unauthenticated do
      root to: 'sportactions#ranking', as: :unauthenticated_root
      get 'ranking' => 'sportactions#ranking'

    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :sport
  belongs_to :user
  belongs_to :employee
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :sportactions
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :sportactions
  has_many :sports, :through => :actions
  has_many :employees, :through => :actions

  validates :sportname, presence: true
  validates :pointsperaction, presence: true
end

app/models/sportaction.rb
class Sportaction < ApplicationRecord
  belongs_to :sport
  belongs_to :user
  belongs_to :employee
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sportactions
  has_many :sports, :through => :actions
  has_many :employees, :through => :actions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :department])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @department_array = ['Business Intelligence','Brand & Communication','Business Development','CFO Staff','Engineering','Enterprise Apps & Infrastructure','Finance','Human Resources','International Strategy & New Markets','Office Management','Online Marketing','Operations','Private Label','Product','Sales & Merchandizing','Vendor Management']
    @employee = Employee.new
  end

  def create
    if Employee.where("employeename = ?", employee_params[:employeename]) == []
      @employee = Employee.new(employee_params)
      @employee.save
      redirect_to pages_about_path
    else
      redirect_to new_employee_path
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:employeename, :department)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/sportactions_controller.rb
class SportactionsController < ApplicationController
  def new
    @sportaction = Sportaction.new
    @sports = Sport.pluck(:sportname)
    @employees = Employee.pluck(:employeename)
    #respond_to do |format|
    #  format.js
    #  format.html
    #end
  end

  def index
    @sportactions = Sportaction.all.order('sportactions.created_at DESC')
  end

  def create
    current_user_id = current_user.id
    date = "#{action_params["datum(1i)"]}-#{action_params["datum(2i)"]}-#{action_params["datum(3i)"]}"

    @sportaction = Sportaction.new(datum: date, user_id: current_user_id)


    @sportaction.sport = Sport.where("sportname = ?", action_params[:sport]).first
    @sportaction.employee = Employee.where("employeename = ?", action_params[:employee]).first

    if @sportaction.save
      @sportaction.save!
      redirect_to ranking_path
    else
      @sportaction = Sportaction.new
      redirect_to departmentranking
    end
  end

  def destroy
    @sportaction = Sportaction.find(params[:id])
    @sportaction.destroy
    redirect_to sportactions_path
  end

  def ranking
    sql = "SELECT e.id, e.employeename, sum(s.pointsperaction) as totalpoints FROM sportactions a left join sports s on s.id=a.sport_id left join employees e on e.id=a.employee_id group by e.id, e.employeename ORDER BY totalpoints desc"
    @actionranking = ActiveRecord::Base.connection.execute(sql)

    sql_dep = "SELECT e.department, sum(s.pointsperaction) as totalpoints FROM sportactions a left join sports s on s.id=a.sport_id left join employees e on e.id=a.employee_id group by e.department ORDER BY totalpoints desc"
    @departmentranking = ActiveRecord::Base.connection.execute(sql_dep)
    render "pages/dashboard"
  end

  private

  def action_params
    params.require(:sportaction).permit(:datum, :sport, :employee)
  end

end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

  def index
    @sports = Sport.all

  end

  def show
    @sport = Sport.new
    @user_not_logged = !user_signed_in?

    @sports = Sport.where("sport = ?", params[:id])

  end

  def new
    @sport = Sport.new
  end

  def create
    if Sport.where("sportname = ?", sport_params[:sportname]) == []
      @sport = Sport.new(sport_params)
      @sport.save
      redirect_to pages_about_path
    else
      redirect_to new_sport_path
    end
  end

  def edit
    # missing function for updating points for a sport
  end

  def update
    @sport.update(sport_params)
    redirect_to sport_path(@sport)
  end

  def destroy
    @sport.delete
    redirect_to pages_about_path
  end

  private

  def set_sport
    @sport = Sport.find(params[:id])
  end

  def sport_params
    params.require(:sport).permit(:sportname, :pointsperaction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actions/new.html.erb
<div class="wrapper">

  <div class="container container-boxes">
        <div class="row">
          <div class="col-xs-12 col-md-6 left-form-container">
            <h2> Add an Activity </h2>

            <div class="row">
              <div class="col-md-12">
                <%= simple_form_for @action do |f| %>
                <%= f.input :datum, label: 'Datum' %>
              </div>
              <div class="col-md-6 col-xs-12">
                <%= f.input :sport, as: :select, collection: @sports %>
              </div>

              <div class="col-md-6 col-xs-12">
                <%= f.input :employee, label: 'Employee?',as: :select, collection: @employees %>
              </div>



              <div class="col-md-6 col-xs-12">
                <div class="photo-input">

                  <%= f.button :submit %>
                </div>


              </div>
              <% end %>
            </div>
          </div>


      </div>

  </div>
</div>

app/views/employees/new.html.erb
<% departments = ['Business Intelligence','HR', 'Marketing'] %>

<div class="wrapper">

  <div class="container container-boxes">
        <div class="row">
          <div class="col-xs-12 col-md-6 left-form-container">
            <h2> Create an Employee </h2>

            <div class="row">
              <div class="col-md-12">
                <%= simple_form_for @employee do |f| %>
                <%= f.input :employeename, label: 'Name' %>
              </div>
              <div class="col-md-6 col-xs-12">
                <%= f.input :department, as: :select, collection: @department_array %>
              </div>


              <div class="col-md-6 col-xs-12">

                  <%= f.button :submit, :class => "btn btn-gradient" %>

              </div>
              <% end %>
            </div>
          </div>


      </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>NO SWEAT NO BEAUTY</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="card-product">

    <%= link_to "Add Sportactivity", new_sportaction_path %>

</div>

<div class="card-product">

     <%= link_to "See all Sportactivities", sportactions_path %>

</div>

<div class="card-product">

    <%= link_to "Create Employee", new_employee_path %>

</div>

<div class="card-product">

     <%= link_to "Create Sport", new_sport_path %>

</div>

<div class="card-product">

     <%= link_to "See all Sports", sports_path %>

</div>

<div class="card-product">

     <%= link_to "Ranking", ranking_path %>

</div>

app/views/pages/dashboard.html.erb
<div class="card-category">
  <h1>RANKING</h1>
</div>

<% x = 0 %>
<% @actionranking.each do |employee| %>
<% x += 1 %>
<div class="card-product">
  <h1> <%= "##{x}" %> </h1>
  <div class="card-product-infos">
    <h2> <%= employee["employeename"] %>  </h2>
    <h3><%= "Punkte: #{employee["totalpoints"]}" %></h3>
  </div>
</div>
<% end %>

<br>
<br>
<br>

<div class="card-category">
  <h1>DEPARTMENT<br>RANKING</h1>
</div>

<% y = 0 %>

<% @departmentranking.each do |department| %>
<% y += 1 %>
<div class="card-product">
  <h1> <%= "##{y}" %> </h1>
  <div class="card-product-infos">
    <h2> <%= department["department"] %>  </h2>
    <h3><%= "Punkte: #{department["totalpoints"]}" %></h3>
  </div>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

    <%= link_to (image_tag "logo.png", height: 50), ranking_path %>




  <!-- Right Navigation -->


  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">


        <div class="navbar-wagon-right hidden-xs hidden-sm">

          <% if user_signed_in? %>
          <li> <%= link_to 'Menü', pages_about_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li> <%= link_to 'Ranking', ranking_path, class: "navbar-wagon-item navbar-wagon-link" %></li>

          <%= link_to "Logout", destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-link",  :method => :delete %>


          <% else %>
            <!-- Login link (when logged out) -->
            <li> <%= link_to 'Ranking', ranking_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>

          <% end %>
        </div>
      </ul>
    </div>
  </div>
</div>

app/views/sportactions/index.html.erb
<h1>All Sportactivities</h1>

<% @sportactions.each do |sportaction| %>

  <div class="card-product-list">

    <div class="card-product-infos">
      <h5> <%= sportaction.datum %> //<%= sportaction.employee.employeename%> // <%=  sportaction.sport.sportname  %> // <%= sportaction.sport.pointsperaction %> Punkte </h5>
      <h5> created at: <%=  sportaction.created_at %> </h5>
      <div>
      <%= link_to 'Delete', sportaction, method: :delete %>
      </div>
    </div>
  </div>

<% end %>

app/views/sportactions/new.html.erb
<div class="wrapper">

  <div class="container container-boxes">
        <div class="row">
          <div class="col-xs-12 col-md-6 left-form-container">
            <h2> Add an Activity </h2>

            <div class="row">
              <div class="col-md-12">
                <%= simple_form_for @sportaction do |f| %>
                <%= f.input :datum, as: :date , label: 'Datum' %>
              </div>
              <div class="col-md-6 col-xs-12">
                <%= f.input :sport, as: :select, collection: @sports %>
              </div>

              <div class="col-md-6 col-xs-12">
                <%= f.input :employee, label: 'Employee?',as: :select, collection: @employees %>
              </div>

              <div class="col-md-6 col-xs-12">

                  <%= f.button :submit, :class => "btn btn-gradient" %>
                 <% end %>
              </div>

            </div>
          </div>


      </div>

  </div>
</div>

app/views/sports/index.html.erb
<% @sports.each do |sport| %>
    <div class="card-product">

        <div class="card-product-infos">
            <h2><%= sport.sportname %> // Punkte: <%= sport.pointsperaction %> </h2>
        </div>

    </div>

<% end %>

app/views/sports/new.html.erb
<div class="wrapper">

  <div class="container container-boxes">
        <div class="row">
          <div class="col-xs-12 col-md-6 left-form-container">
            <h2> Create a new sport </h2>

            <div class="row">
              <div class="col-md-12">
                <%= simple_form_for @sport do |f| %>
                <%= f.input :sportname, label: 'Sportart' %>
              </div>


              <div class="col-md-6 col-xs-12">
                <%= f.input :pointsperaction, label: 'How many points per session?' %>
              </div>
              <div><%= f.button :submit, :class => "btn btn-gradient" %></div>
              <% end %>

            </div>
          </div>


      </div>

  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>